name: Deploy to production environment

# Controls when the action will run
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [production-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-s3-apps-workflow:
    # Replace with repository name
    name: CD caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    uses: graasp/graasp-deploy/.github/workflows/cdeployment-s3-apps.yml@main
    # Replace input build-folder or version if needed.
    with:
      build-folder: 'build'
      version: 'latest'
      tag: ${{ github.event.client_payload.tag }}
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      aws-access-key-id:
      aws-secret-access-key:
      aws-region:
      aws-s3-bucket-name:
      cloudfront-distribution-id:
      app-id:
      graasp-domain:
