name: Deploy to production environment

# Controls when the action will run
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [production-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-ecs-workflow:
    # Replace with repository name
    name: CD caller template
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    uses: graasp/graasp-deploy/.github/workflows/cdeployment-ecs-explorer.yml@main
    # Replace input ecs-task-definition with template file. Format: '.aws/<name>-prod.json'
    with:
      ecs-task-definition:
      tag: ${{ github.event.client_payload.tag }}
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      aws-access-key-id:
      aws-secret-access-key:
      aws-region:
      ecs-cluster:
      ecs-service:
      ecr-repository:
      container-name-explorer:
      next-public-api-host:
      next-public-google-analytics-id:
      next-public-graasp-auth-host:
      next-public-graasp-builder-host:
      next-public-graasp-perform-host:
      next-public-graasper-id:
      next-public-published-tag-id:
      next-public-sentry-dsn:
      next-public-domain:
      port:
